### ISSUE TITLE
Release missmatch, need git tag for 2.0.2

### ISSUE THREAD

**Issue by alerque** [ToxicFrog/vstruct#37]
We need a git tag to match the current latest luarocks release.

**Comment by ToxicFrog** [comment]
The only difference between "2.0.1" and "2.0.2" is the rockspec itself, which I didn't write; I'm not sure where that version number comes from.

**Comment by alerque** [comment]
The version number comes from Lua Rocks where the Rockspec with that version has been posted. Given the chaos that is is the Lua ecosystem it is not uncommon for Lua Rocks vs. upstream source code to be out of sync.

I would suggest just tagging the current HEAD as 2.0.2 for now to make it easier to download the source from this repository and have the version number than many projects depend on. For example in Arch Linux we like packaging upstream source code over LuaRocks where possible.

After that I would suggest applying for module ownership of the module on LuaRocks so you can keep them in sync in the future and make it a bit more canonical.

**Comment by deepakjois** [comment]
I wrote the Rockspec files. There is actually a difference between the rockspecs. The 2.0.2 spec sets a lower bound on the Lua version to `< 5.3` because vstruct does not work with Lua 5.3. For some reason I must have overlooked the fact that the repo did not have a tag `v2.0.2`. That should be easy to fix, but I dont believe I have rights to push to this repo, so @ToxicFrog will have to do it.

I even attempted a fix for Lua 5.3 but I was stuck.
https://github.com/ToxicFrog/vstruct/pull/35

**Comment by ToxicFrog** [comment]
I've tagged v2.0.2.
Working on 5.3 (without breaking 5.1/.2 & luajit) is next on my list, and I'm sorry I've let that languish for so long. I should be able to use your code as a starting point; thanks for that.
